---
- name: Deploy simple webserver
  hosts: web
  become: true
  gather_facts: false
  
  tasks:
  - ansible.builtin.debug:
      var: hostvars

  - name: Install apache webserver package
    ansible.builtin.package:
      name: "{{ webserver_package }}"
      state: present

  - name: Copy in an index.html file
    ansible.builtin.copy:
      src: files/index.html
      dest: /var/www/html/index.html

  - name: Start and enable apache webserver
    become: true
    ansible.builtin.service:
      name: "{{ webserver_service }}"
      state: started
      enabled: true


